/*
 * Friendly display names for gamedig game IDs.
 * Used in the standard embed footer to show which game a status is for.
 * Source: gamedig/games.txt (release years stripped for cleaner display).
 */
export const GAMEDIG_GAME_NAMES: Readonly<Record<string, string>> = {
  "7d2d": "7 Days to Die",
  "ageofchivalry": "Age of Chivalry",
  "ahl": "Action Half-Life",
  "alienarena": "Alien Arena",
  "alienswarm": "Alien Swarm",
  "americasarmy": "America's Army",
  "americasarmy2": "America's Army 2",
  "americasarmy3": "America's Army 3",
  "americasarmypg": "America's Army: Proving Grounds",
  "aoe2": "Age of Empires 2",
  "arcasimracing": "Arca Sim Racing",
  "arkse": "Ark: Survival Evolved",
  "arma": "ARMA: Armed Assault",
  "arma2": "ARMA 2",
  "arma2oa": "ARMA 2: Operation Arrowhead",
  "arma3": "ARMA 3",
  "armacwa": "ARMA: Cold War Assault",
  "armagetron": "Armagetron Advanced",
  "armar": "ARMA: Resistance",
  "armare": "ARMA: Reforger",
  "as": "Action: Source",
  "asa": "Ark: Survival Ascended",
  "assettocorsa": "Assetto Corsa",
  "atlas": "Atlas",
  "avorion": "Avorion",
  "avp2": "Aliens versus Predator 2",
  "avp2010": "Aliens vs. Predator",
  "baldursgate": "Baldur's Gate",
  "ballisticoverkill": "Ballistic Overkill",
  "barotrauma": "Barotrauma",
  "bat1944": "Battalion 1944",
  "bd": "Base Defense",
  "bf1942": "Battlefield 1942",
  "bf2": "Battlefield 2",
  "bf2142": "Battlefield 2142",
  "bf3": "Battlefield 3",
  "bf4": "Battlefield 4",
  "bfbc2": "Battlefield: Bad Company 2",
  "bfh": "Battlefield Hardline",
  "bfv": "Battlefield Vietnam",
  "blackmesa": "Black Mesa",
  "brainbread": "BrainBread",
  "brainbread2": "BrainBread 2",
  "breach": "Breach",
  "breed": "Breed",
  "brink": "Brink",
  "bs": "Blade Symphony",
  "buildandshoot": "Build and Shoot / Ace of Spades Classic",
  "cacrenegade": "Command and Conquer: Renegade",
  "callofjuarez": "Call of Juarez",
  "chaser": "Chaser",
  "chivalry": "Chivalry: Medieval Warfare",
  "chrome": "Chrome",
  "cod": "Call of Duty",
  "cod2": "Call of Duty 2",
  "cod3": "Call of Duty 3",
  "cod4": "Call of Duty 4: Modern Warfare",
  "codenamecure": "Codename CURE",
  "codenameeagle": "Codename Eagle",
  "codmw2": "Call of Duty: Modern Warfare 2",
  "codmw3": "Call of Duty: Modern Warfare 3",
  "coduo": "Call of Duty: United Offensive",
  "codwaw": "Call of Duty: World at War",
  "colonysurvival": "Colony Survival",
  "commandos3": "Commandos 3: Destination Berlin",
  "conanexiles": "Conan Exiles",
  "contactjack": "Contract J.A.C.K.",
  "contagion": "Contagion",
  "corekeeper": "Core Keeper",
  "creativerse": "Creativerse",
  "crossracing": "Cross Racing Championship Extreme 2005",
  "crysis": "Crysis",
  "crysis2": "Crysis 2",
  "crysiswars": "Crysis Wars",
  "cs15": "Counter-Strike 1.5",
  "cs16": "Counter-Strike 1.6",
  "cs2": "Counter-Strike 2",
  "cs2d": "CS2D",
  "cscz": "Counter-Strike: Condition Zero",
  "csgo": "Counter-Strike: Global Offensive",
  "css": "Counter-Strike: Source",
  "dab": "Double Action: Boogaloo",
  "daikatana": "Daikatana",
  "darkesthour": "Darkest Hour: Europe '44-'45",
  "dayofdragons": "Day of Dragons",
  "daysofwar": "Days of War",
  "dayz": "DayZ",
  "dayzmod": "DayZ Mod",
  "deadlydozenpt": "Deadly Dozen: Pacific Theater",
  "descent3": "Descent 3",
  "deusex": "Deus Ex",
  "devastation": "Devastation",
  "dh2005": "Deer Hunter 2005",
  "dinodday": "Dino D-Day",
  "dirttrackracing2": "Dirt Track Racing 2",
  "discord": "Discord",
  "dmc": "Deathmatch Classic",
  "dmomam": "Dark Messiah of Might and Magic",
  "dnl": "Dark and Light",
  "dod": "Day of Defeat",
  "dods": "Day of Defeat: Source",
  "doi": "Day of Infamy",
  "doom3": "Doom 3",
  "dota2": "Dota 2",
  "drakan": "Drakan: Order of the Flame",
  "dst": "Don't Starve Together",
  "dys": "Dystopia",
  "eco": "Eco",
  "eldewrito": "Halo Online (ElDewrito)",
  "em": "Empires Mod",
  "empyrion": "Empyrion - Galactic Survival",
  "etqw": "Enemy Territory: Quake Wars",
  "f12002": "Formula One 2002",
  "f1c9902": "F1 Challenge '99-'02",
  "farcry": "Far Cry",
  "farcry2": "Far Cry 2",
  "fear": "F.E.A.R.",
  "ffow": "Frontlines: Fuel of War",
  "fivem": "Grand Theft Auto V - FiveM",
  "flashpoint": "Operation Flashpoint: Cold War Crisis",
  "flashpointresistance": "Operation Flashpoint: Resistance",
  "fof": "Fistful of Frags",
  "forrest": "The Forrest",
  "fortressforever": "Fortress Forever",
  "garrysmod": "Garry's Mod",
  "geneshift": "Geneshift",
  "ges": "GoldenEye: Source",
  "giantscitizenkabuto": "Giants: Citizen Kabuto",
  "globaloperations": "Global Operations",
  "gore": "Gore: Ultimate Soldier",
  "graw": "Tom Clancy's Ghost Recon Advanced Warfighter",
  "graw2": "Tom Clancy's Ghost Recon Advanced Warfighter 2",
  "groundbreach": "Ground Breach",
  "gunmanchronicles": "Gunman Chronicles",
  "had2": "Hidden & Dangerous 2",
  "halo": "Halo",
  "halo2": "Halo 2",
  "heretic2": "Heretic II",
  "hexen2": "Hexen II",
  "hidden": "The Hidden",
  "hl2dm": "Half-Life 2: Deathmatch",
  "hldm": "Half-Life Deathmatch",
  "hldms": "Half-Life Deathmatch: Source",
  "hll": "Hell Let Loose",
  "hlopfor": "Half-Life: Opposing Force",
  "homefront": "Homefront",
  "homeworld2": "Homeworld 2",
  "hurtworld": "Hurtworld",
  "igi2": "I.G.I.-2: Covert Strike",
  "il2": "IL-2 Sturmovik",
  "insurgency": "Insurgency",
  "insurgencymic": "Insurgency: Modern Infantry Combat",
  "insurgencysandstorm": "Insurgency: Sandstorm",
  "ironstorm": "Iron Storm",
  "isle": "The Isle",
  "jamesbondnightfire": "James Bond 007: Nightfire",
  "jc2mp": "Just Cause 2 - Multiplayer",
  "jc3mp": "Just Cause 3 - Multiplayer",
  "killingfloor": "Killing Floor",
  "killingfloor2": "Killing Floor 2",
  "kingpin": "Kingpin: Life of Crime",
  "kisspc": "Kiss: Psycho Circus: The Nightmare Child",
  "kspdmp": "Kerbal Space Program - DMP Multiplayer",
  "kzmod": "Kreedz Climbing",
  "left4dead": "Left 4 Dead",
  "left4dead2": "Left 4 Dead 2",
  "m2mp": "Mafia II - Multiplayer",
  "m2o": "Mafia II - Online",
  "medievalengineers": "Medieval Engineers",
  "minecraft": "Minecraft",
  "minecraftbe": "Minecraft: Bedrock Edition",
  "minecraftpe": "Minecraft: Bedrock Edition",
  "minecraftping": "Minecraft",
  "mnc": "Monday Night Combat",
  "moh2010": "Medal of Honor",
  "mohaa": "Medal of Honor: Allied Assault",
  "mohab": "Medal of Honor: Airborne",
  "mohbt": "Medal of Honor: Allied Assault Breakthrough",
  "mohpa": "Medal of Honor: Pacific Assault",
  "mohsh": "Medal of Honor: Allied Assault Spearhead",
  "mohwf": "Medal of Honor: Warfighter",
  "mordhau": "Mordhau",
  "mtasa": "Grand Theft Auto: San Andreas - Multi Theft Auto",
  "mtavc": "Grand Theft Auto: Vice City - Multi Theft Auto",
  "mumble": "Mumble - GTmurmur Plugin",
  "mumbleping": "Mumble - Lightweight",
  "mutantfactions": "Geneshift",
  "nab": "Nerf Arena Blast",
  "nascarthunder2004": "NASCAR Thunder 2004",
  "netpanzer": "netPanzer",
  "nexuiz": "Nexuiz",
  "nfshp2": "Need for Speed: Hot Pursuit 2",
  "nitrofamily": "Nitro Family",
  "nmrih": "No More Room in Hell",
  "nolf": "The Operative: No One Lives Forever",
  "nolf2": "No One Lives Forever 2: A Spy in H.A.R.M.'s Way",
  "ns": "Natural Selection",
  "ns2": "Natural Selection 2",
  "nucleardawn": "Nuclear Dawn",
  "nwn": "Neverwinter Nights",
  "nwn2": "Neverwinter Nights 2",
  "ohd": "Operation: Harsh Doorstop",
  "onset": "Onset",
  "openarena": "OpenArena",
  "openttd": "OpenTTD",
  "operationflashpoint": "Operation Flashpoint: Cold War Crisis",
  "painkiller": "Painkiller",
  "pc": "Project Cars",
  "pc2": "Project Cars 2",
  "pixark": "PixARK",
  "postal2": "Postal 2",
  "prbf2": "Project Reality: Battlefield 2",
  "prey": "Prey",
  "primalcarnage": "Primal Carnage: Extinction",
  "przomboid": "Project Zomboid",
  "ps": "Post Scriptum",
  "pvkii": "Pirates, Vikings, and Knights II",
  "quake1": "Quake 1: QuakeWorld",
  "quake2": "Quake 2",
  "quake3": "Quake 3: Arena",
  "quake4": "Quake 4",
  "quakelive": "Quake Live",
  "r6": "Rainbow Six",
  "r6ravenshield": "Rainbow Six 3: Raven Shield",
  "r6roguespear": "Rainbow Six 2: Rogue Spear",
  "ragdollkungfu": "Rag Doll Kung Fu",
  "rallisportchallenge": "RalliSport Challenge",
  "rallymasters": "Rally Masters",
  "redline": "Redline",
  "redm": "Red Dead Redemption 2 - RedM",
  "redorchestra": "Red Orchestra",
  "redorchestra2": "Red Orchestra 2",
  "redorchestraost": "Red Orchestra: Ostfront 41-45",
  "rfactor": "rFactor",
  "ricochet": "Ricochet",
  "riseofnations": "Rise of Nations",
  "risingworld": "Rising World",
  "ror2": "Risk of Rain 2",
  "rs2": "Rising Storm 2: Vietnam",
  "rtcw": "Return to Castle Wolfenstein",
  "rune": "Rune",
  "rust": "Rust",
  "samp": "San Andreas Multiplayer",
  "saomp": "San Andreas OpenMP",
  "savage2": "Savage 2: A Tortured Soul",
  "shatteredhorizon": "Shattered Horizon",
  "ship": "The Ship",
  "shogo": "Shogo",
  "shootmania": "Shootmania",
  "sin": "SiN",
  "sinep": "SiN Episodes",
  "sof": "Soldier of Fortune",
  "sof2": "Soldier of Fortune 2",
  "soldat": "Soldat",
  "sonsoftheforest": "Sons Of The Forest",
  "spaceengineers": "Space Engineers",
  "squad": "Squad",
  "ss": "Serious Sam",
  "ss2": "Serious Sam 2",
  "stalker": "S.T.A.L.K.E.R.",
  "starbound": "Starbound",
  "starmade": "StarMade",
  "starsiege": "Starsiege",
  "stbc": "Star Trek: Bridge Commander",
  "stn": "Survive the Nights",
  "stvef": "Star Trek: Voyager - Elite Force",
  "stvef2": "Star Trek: Voyager - Elite Force 2",
  "suicidesurvival": "Suicide Survival",
  "svencoop": "Sven Coop",
  "swat4": "SWAT 4",
  "swbf": "Star Wars: Battlefront",
  "swbf2": "Star Wars: Battlefront 2",
  "swjk": "Star Wars Jedi Knight: Jedi Academy",
  "swjk2": "Star Wars Jedi Knight II: Jedi Outcast",
  "swrc": "Star Wars: Republic Commando",
  "synergy": "Synergy",
  "tacticalops": "Tactical Ops",
  "takeonhelicopters": "Take On Helicopters",
  "teamfactor": "Team Factor",
  "teamspeak2": "Teamspeak 2",
  "teamspeak3": "Teamspeak 3",
  "terminus": "Terminus",
  "terraria": "Terraria - TShock",
  "tf2": "Team Fortress 2",
  "tfc": "Team Fortress Classic",
  "theforest": "The Forest",
  "thefront": "The Front",
  "thps3": "Tony Hawk's Pro Skater 3",
  "thps4": "Tony Hawk's Pro Skater 4",
  "thu2": "Tony Hawk's Underground 2",
  "towerunite": "Tower Unite",
  "trackmania2": "Trackmania 2",
  "trackmaniaforever": "Trackmania Forever",
  "tremulous": "Tremulous",
  "tribes1": "Tribes 1: Starsiege",
  "tribesvengeance": "Tribes: Vengeance",
  "tron20": "Tron 2.0",
  "ts": "The Specalists",
  "tshock": "Terraria - TShock",
  "turok2": "Turok 2",
  "universalcombat": "Universal Combat",
  "unreal": "Unreal",
  "unturned": "Unturned",
  "urbanterror": "Urban Terror",
  "ut": "Unreal Tournament",
  "ut2003": "Unreal Tournament 2003",
  "ut2004": "Unreal Tournament 2004",
  "ut3": "Unreal Tournament 3",
  "v8supercar": "V8 Supercar Challenge",
  "valheim": "Valheim",
  "vcmp": "Vice City Multiplayer",
  "ventrilo": "Ventrilo",
  "vietcong": "Vietcong",
  "vietcong2": "Vietcong 2",
  "vrising": "V Rising",
  "vs": "Vampire Slayer",
  "warfork": "Warfork",
  "warsow": "Warsow",
  "wheeloftime": "Wheel of Time",
  "wolfenstein2009": "Wolfenstein 2009",
  "wolfensteinet": "Wolfenstein: Enemy Territory",
  "wurm": "Wurm Unlimited",
  "xpandrally": "Xpand Rally",
  "zombiemaster": "Zombie Master",
  "zps": "Zombie Panic: Source",
};
