/*
 * Full list of gamedig 4.3.1 supported game IDs.
 * Used for /status game: slash-command autocomplete.
 * Source: gamedig/games.txt (extracted from installed gamedig 4.3.1).
 */
export const GAMEDIG_GAME_IDS: readonly string[] = [
  "7d2d", "ageofchivalry", "ahl", "alienarena", "alienswarm", "americasarmy",
  "americasarmy2", "americasarmy3", "americasarmypg", "aoe2", "arcasimracing", "arkse",
  "arma", "arma2", "arma2oa", "arma3", "armacwa", "armagetron",
  "armar", "armare", "as", "asa", "assettocorsa", "atlas",
  "avorion", "avp2", "avp2010", "baldursgate", "ballisticoverkill", "barotrauma",
  "bat1944", "bd", "bf1942", "bf2", "bf2142", "bf3",
  "bf4", "bfbc2", "bfh", "bfv", "blackmesa", "brainbread",
  "brainbread2", "breach", "breed", "brink", "bs", "buildandshoot",
  "cacrenegade", "callofjuarez", "chaser", "chivalry", "chrome", "cod",
  "cod2", "cod3", "cod4", "codenamecure", "codenameeagle", "codmw2",
  "codmw3", "coduo", "codwaw", "colonysurvival", "commandos3", "conanexiles",
  "contactjack", "contagion", "corekeeper", "creativerse", "crossracing", "crysis",
  "crysis2", "crysiswars", "cs15", "cs16", "cs2", "cs2d",
  "cscz", "csgo", "css", "dab", "daikatana", "darkesthour",
  "dayofdragons", "daysofwar", "dayz", "dayzmod", "deadlydozenpt", "descent3",
  "deusex", "devastation", "dh2005", "dinodday", "dirttrackracing2", "discord",
  "dmc", "dmomam", "dnl", "dod", "dods", "doi",
  "doom3", "dota2", "drakan", "dst", "dys", "eco",
  "eldewrito", "em", "empyrion", "etqw", "f12002", "f1c9902",
  "farcry", "farcry2", "fear", "ffow", "fivem", "flashpoint",
  "flashpointresistance", "fof", "forrest", "fortressforever", "garrysmod", "geneshift",
  "ges", "giantscitizenkabuto", "globaloperations", "gore", "graw", "graw2",
  "groundbreach", "gunmanchronicles", "had2", "halo", "halo2", "heretic2",
  "hexen2", "hidden", "hl2dm", "hldm", "hldms", "hll",
  "hlopfor", "homefront", "homeworld2", "hurtworld", "igi2", "il2",
  "insurgency", "insurgencymic", "insurgencysandstorm", "ironstorm", "isle", "jamesbondnightfire",
  "jc2mp", "jc3mp", "killingfloor", "killingfloor2", "kingpin", "kisspc",
  "kspdmp", "kzmod", "left4dead", "left4dead2", "m2mp", "m2o",
  "medievalengineers", "minecraft", "minecraftbe", "minecraftpe", "minecraftping", "mnc",
  "moh2010", "mohaa", "mohab", "mohbt", "mohpa", "mohsh",
  "mohwf", "mordhau", "mtasa", "mtavc", "mumble", "mumbleping",
  "mutantfactions", "nab", "nascarthunder2004", "netpanzer", "nexuiz", "nfshp2",
  "nitrofamily", "nmrih", "nolf", "nolf2", "ns", "ns2",
  "nucleardawn", "nwn", "nwn2", "ohd", "onset", "openarena",
  "openttd", "operationflashpoint", "painkiller", "pc", "pc2", "pixark",
  "postal2", "prbf2", "prey", "primalcarnage", "przomboid", "ps",
  "pvkii", "quake1", "quake2", "quake3", "quake4", "quakelive",
  "r6", "r6ravenshield", "r6roguespear", "ragdollkungfu", "rallisportchallenge", "rallymasters",
  "redline", "redm", "redorchestra", "redorchestra2", "redorchestraost", "rfactor",
  "ricochet", "riseofnations", "risingworld", "ror2", "rs2", "rtcw",
  "rune", "rust", "samp", "saomp", "savage2", "shatteredhorizon",
  "ship", "shogo", "shootmania", "sin", "sinep", "sof",
  "sof2", "soldat", "sonsoftheforest", "spaceengineers", "squad", "ss",
  "ss2", "stalker", "starbound", "starmade", "starsiege", "stbc",
  "stn", "stvef", "stvef2", "suicidesurvival", "svencoop", "swat4",
  "swbf", "swbf2", "swjk", "swjk2", "swrc", "synergy",
  "tacticalops", "takeonhelicopters", "teamfactor", "teamspeak2", "teamspeak3", "terminus",
  "terraria", "tf2", "tfc", "theforest", "thefront", "thps3",
  "thps4", "thu2", "towerunite", "trackmania2", "trackmaniaforever", "tremulous",
  "tribes1", "tribesvengeance", "tron20", "ts", "tshock", "turok2",
  "universalcombat", "unreal", "unturned", "urbanterror", "ut", "ut2003",
  "ut2004", "ut3", "v8supercar", "valheim", "vcmp", "ventrilo",
  "vietcong", "vietcong2", "vrising", "vs", "warfork", "warsow",
  "wheeloftime", "wolfenstein2009", "wolfensteinet", "wurm", "xpandrally", "zombiemaster",
  "zps"
];
