/*
 * Friendly display names for gamedig 4.3.1 protocol IDs.
 * Used to render the game name in embed footers.
 * Source: gamedig/node-gamedig GAMES_LIST.md at v4.3.1.
 */
export const GAMEDIG_GAME_NAMES: Readonly<Record<string, string>> = {
  as: "Action: Source",
  ahl: "Action Half-Life",
  ageofchivalry: "Age of Chivalry",
  aoe2: "Age of Empires 2",
  alienarena: "Alien Arena",
  alienswarm: "Alien Swarm",
  avp2: "Aliens versus Predator 2",
  avp2010: "Aliens vs. Predator",
  americasarmy: "America's Army",
  americasarmy2: "America's Army 2",
  americasarmy3: "America's Army 3",
  americasarmypg: "America's Army: Proving Grounds",
  arcasimracing: "Arca Sim Racing",
  arkse: "Ark: Survival Evolved",
  arma2: "ARMA 2",
  arma2oa: "ARMA 2: Operation Arrowhead",
  arma3: "ARMA 3",
  arma: "ARMA: Armed Assault",
  armacwa: "ARMA: Cold War Assault",
  armar: "ARMA: Resistance",
  armare: "ARMA: Reforger",
  armagetron: "Armagetron Advanced",
  asa: "Ark: Survival Ascended",
  assettocorsa: "Assetto Corsa",
  atlas: "Atlas",
  avorion: "Avorion",
  baldursgate: "Baldur's Gate",
  ballisticoverkill: "Ballistic Overkill",
  barotrauma: "Barotrauma",
  bat1944: "Battalion 1944",
  bf1942: "Battlefield 1942",
  bf2: "Battlefield 2",
  bf2142: "Battlefield 2142",
  bf3: "Battlefield 3",
  bf4: "Battlefield 4",
  bfh: "Battlefield Hardline",
  bfv: "Battlefield Vietnam",
  bfbc2: "Battlefield: Bad Company 2",
  bd: "Base Defense",
  blackmesa: "Black Mesa",
  brainbread: "BrainBread",
  brainbread2: "BrainBread 2",
  breach: "Breach",
  breed: "Breed",
  brink: "Brink",
  bs: "Blade Symphony",
  buildandshoot: "Build and Shoot / Ace of Spades Classic",
  cod: "Call of Duty",
  cod2: "Call of Duty 2",
  cod3: "Call of Duty 3",
  cod4: "Call of Duty 4: Modern Warfare",
  codmw2: "Call of Duty: Modern Warfare 2",
  codmw3: "Call of Duty: Modern Warfare 3",
  coduo: "Call of Duty: United Offensive",
  codwaw: "Call of Duty: World at War",
  callofjuarez: "Call of Juarez",
  chaser: "Chaser",
  chivalry: "Chivalry: Medieval Warfare",
  chrome: "Chrome",
  codenamecure: "Codename CURE",
  codenameeagle: "Codename Eagle",
  colonysurvival: "Colony Survival",
  cacrenegade: "Command and Conquer: Renegade",
  commandos3: "Commandos 3: Destination Berlin",
  conanexiles: "Conan Exiles",
  contagion: "Contagion",
  contactjack: "Contract J.A.C.K.",
  corekeeper: "Core Keeper",
  cs15: "Counter-Strike 1.5",
  cs16: "Counter-Strike 1.6",
  cs2d: "CS2D",
  cscz: "Counter-Strike: Condition Zero",
  csgo: "Counter-Strike: Global Offensive",
  css: "Counter-Strike: Source",
  cs2: "Counter-Strike 2",
  creativerse: "Creativerse",
  crossracing: "Cross Racing Championship Extreme 2005",
  crysis: "Crysis",
  crysis2: "Crysis 2",
  crysiswars: "Crysis Wars",
  dab: "Double Action: Boogaloo",
  daikatana: "Daikatana",
  dnl: "Dark and Light",
  dmomam: "Dark Messiah of Might and Magic",
  darkesthour: "Darkest Hour: Europe '44-'45",
  dod: "Day of Defeat",
  dods: "Day of Defeat: Source",
  dayofdragons: "Day of Dragons",
  doi: "Day of Infamy",
  daysofwar: "Days of War",
  dayz: "DayZ",
  dayzmod: "DayZ Mod",
  deadlydozenpt: "Deadly Dozen: Pacific Theater",
  dh2005: "Deer Hunter 2005",
  descent3: "Descent 3",
  deusex: "Deus Ex",
  devastation: "Devastation",
  dinodday: "Dino D-Day",
  dirttrackracing2: "Dirt Track Racing 2",
  discord: "Discord",
  dmc: "Deathmatch Classic",
  dst: "Don't Starve Together",
  doom3: "Doom 3",
  dota2: "Dota 2",
  drakan: "Drakan: Order of the Flame",
  dystopia: "Dystopia",
  eco: "Eco",
  eldewrito: "Halo Online - ElDewrito",
  empyrion: "Empyrion - Galactic Survival",
  empiresmod: "Empires Mod",
  etqw: "Enemy Territory: Quake Wars",
  fear: "F.E.A.R.",
  f1c9902: "F1 Challenge '99-'02",
  farcry: "Far Cry",
  farcry2: "Far Cry 2",
  f12002: "Formula One 2002",
  fof: "Fistful of Frags",
  fortressforever: "Fortress Forever",
  ffow: "Frontlines: Fuel of War",
  garrysmod: "Garry's Mod",
  geneshift: "Geneshift",
  mutantfactions: "Mutant Factions",
  giantscitizenkabuto: "Giants: Citizen Kabuto",
  globaloperations: "Global Operations",
  ges: "GoldenEye: Source",
  gore: "Gore: Ultimate Soldier",
  fivem: "Grand Theft Auto V - FiveM",
  mtasa: "Grand Theft Auto: San Andreas - Multi Theft Auto",
  mtavc: "Grand Theft Auto: Vice City - Multi Theft Auto",
  groundbreach: "Ground Breach",
  gunmanchronicles: "Gunman Chronicles",
  hl2dm: "Half-Life 2: Deathmatch",
  hldm: "Half-Life Deathmatch",
  hldms: "Half-Life Deathmatch: Source",
  hlopfor: "Half-Life: Opposing Force",
  halo: "Halo",
  halo2: "Halo 2",
  hll: "Hell Let Loose",
  heretic2: "Heretic II",
  hexen2: "Hexen II",
  had2: "Hidden & Dangerous 2",
  homefront: "Homefront",
  homeworld2: "Homeworld 2",
  hurtworld: "Hurtworld",
  igi2: "I.G.I.-2: Covert Strike",
  il2: "IL-2 Sturmovik",
  insurgency: "Insurgency",
  insurgencymic: "Insurgency: Modern Infantry Combat",
  insurgencysandstorm: "Insurgency: Sandstorm",
  ironstorm: "Iron Storm",
  isle: "The Isle",
  jamesbondnightfire: "James Bond 007: Nightfire",
  jc2mp: "Just Cause 2 - Multiplayer",
  jc3mp: "Just Cause 3 - Multiplayer",
  kspdmp: "Kerbal Space Program - DMP Multiplayer",
  killingfloor: "Killing Floor",
  killingfloor2: "Killing Floor 2",
  kingpin: "Kingpin: Life of Crime",
  kisspc: "Kiss: Psycho Circus: The Nightmare Child",
  kzmod: "Kreedz Climbing",
  left4dead: "Left 4 Dead",
  left4dead2: "Left 4 Dead 2",
  m2mp: "Mafia II - Multiplayer",
  m2o: "Mafia II - Online",
  moh2010: "Medal of Honor",
  mohab: "Medal of Honor: Airborne",
  mohaa: "Medal of Honor: Allied Assault",
  mohbt: "Medal of Honor: Allied Assault Breakthrough",
  mohsh: "Medal of Honor: Allied Assault Spearhead",
  mohpa: "Medal of Honor: Pacific Assault",
  mohwf: "Medal of Honor: Warfighter",
  medievalengineers: "Medieval Engineers",
  minecraft: "Minecraft",
  minecraftbe: "Minecraft: Bedrock Edition",
  mnc: "Monday Night Combat",
  mordhau: "Mordhau",
  mumble: "Mumble - GTmurmur Plugin",
  mumbleping: "Mumble - Lightweight",
  nascarthunder2004: "NASCAR Thunder 2004",
  ns: "Natural Selection",
  ns2: "Natural Selection 2",
  nfshp2: "Need for Speed: Hot Pursuit 2",
  nab: "Nerf Arena Blast",
  netpanzer: "netPanzer",
  nwn: "Neverwinter Nights",
  nwn2: "Neverwinter Nights 2",
  nexuiz: "Nexuiz",
  nitrofamily: "Nitro Family",
  nmrih: "No More Room in Hell",
  nolf2: "No One Lives Forever 2: A Spy in H.A.R.M.'s Way",
  nucleardawn: "Nuclear Dawn",
  onset: "Onset",
  ohd: "Operation: Harsh Doorstop",
  openarena: "OpenArena",
  openttd: "OpenTTD",
  ofcwc: "Operation Flashpoint: Cold War Crisis",
  flashpointresistance: "Operation Flashpoint: Resistance",
  painkiller: "Painkiller",
  pc: "Project Cars",
  pc2: "Project Cars 2",
  pixark: "PixARK",
  pvkii: "Pirates, Vikings, and Knights II",
  ps: "Post Scriptum",
  postal2: "Postal 2",
  prey: "Prey",
  primalcarnage: "Primal Carnage: Extinction",
  prbf2: "Project Reality: Battlefield 2",
  przomboid: "Project Zomboid",
  quake1: "Quake 1: QuakeWorld",
  quake2: "Quake 2",
  quake3: "Quake 3: Arena",
  quake4: "Quake 4",
  quakelive: "Quake Live",
  ragdollkungfu: "Rag Doll Kung Fu",
  r6: "Rainbow Six",
  r6roguespear: "Rainbow Six 2: Rogue Spear",
  r6ravenshield: "Rainbow Six 3: Raven Shield",
  rallisportchallenge: "RalliSport Challenge",
  rallymasters: "Rally Masters",
  redorchestra: "Red Orchestra",
  redorchestra2: "Red Orchestra 2",
  redorchestraost: "Red Orchestra: Ostfront 41-45",
  redline: "Redline",
  redm: "Red Dead Redemption 2 - RedM",
  rtcw: "Return to Castle Wolfenstein",
  rfactor: "rFactor",
  ricochet: "Ricochet",
  riseofnations: "Rise of Nations",
  rs2: "Rising Storm 2: Vietnam",
  risingworld: "Rising World",
  ror2: "Risk of Rain 2",
  rune: "Rune",
  rust: "Rust",
  stalker: "S.T.A.L.K.E.R.",
  samp: "San Andreas Multiplayer",
  saomp: "San Andreas OpenMP",
  savage2: "Savage 2: A Tortured Soul",
  sdtd: "7 Days to Die",
  ss: "Serious Sam",
  ss2: "Serious Sam 2",
  shatteredhorizon: "Shattered Horizon",
  shogo: "Shogo",
  shootmania: "Shootmania",
  sin: "SiN",
  sinep: "SiN Episodes",
  soldat: "Soldat",
  sof: "Soldier of Fortune",
  sof2: "Soldier of Fortune 2",
  sonsoftheforest: "Sons Of The Forest",
  spaceengineers: "Space Engineers",
  squad: "Squad",
  stbc: "Star Trek: Bridge Commander",
  stvef: "Star Trek: Voyager - Elite Force",
  stvef2: "Star Trek: Voyager - Elite Force 2",
  swjk2: "Star Wars Jedi Knight II: Jedi Outcast",
  swjk: "Star Wars Jedi Knight: Jedi Academy",
  swbf: "Star Wars: Battlefront",
  swbf2: "Star Wars: Battlefront 2",
  swrc: "Star Wars: Republic Commando",
  starbound: "Starbound",
  starmade: "StarMade",
  starsiege: "Starsiege",
  suicidesurvival: "Suicide Survival",
  stn: "Survive the Nights",
  svencoop: "Sven Coop",
  swat4: "SWAT 4",
  synergy: "Synergy",
  tacticalops: "Tactical Ops",
  takeonhelicopters: "Take On Helicopters",
  teamfactor: "Team Factor",
  tf2: "Team Fortress 2",
  tfc: "Team Fortress Classic",
  teamspeak2: "Teamspeak 2",
  teamspeak3: "Teamspeak 3",
  terminus: "Terminus",
  terraria: "Terraria - TShock",
  forrest: "The Forrest",
  thefront: "The Front",
  hidden: "The Hidden",
  nolf: "The Operative: No One Lives Forever",
  ship: "The Ship",
  ts: "The Specialists",
  graw: "Tom Clancy's Ghost Recon Advanced Warfighter",
  graw2: "Tom Clancy's Ghost Recon Advanced Warfighter 2",
  theforest: "The Forest",
  thps3: "Tony Hawk's Pro Skater 3",
  thps4: "Tony Hawk's Pro Skater 4",
  thu2: "Tony Hawk's Underground 2",
  towerunite: "Tower Unite",
  trackmania2: "Trackmania 2",
  trackmaniaforever: "Trackmania Forever",
  tremulous: "Tremulous",
  tribes1: "Tribes 1: Starsiege",
  tribesvengeance: "Tribes: Vengeance",
  tron20: "Tron 2.0",
  turok2: "Turok 2",
  universalcombat: "Universal Combat",
  unreal: "Unreal",
  ut: "Unreal Tournament",
  ut2003: "Unreal Tournament 2003",
  ut2004: "Unreal Tournament 2004",
  ut3: "Unreal Tournament 3",
  unturned: "Unturned",
  urbanterror: "Urban Terror",
  vrising: "V Rising",
  v8supercar: "V8 Supercar Challenge",
  vs: "Vampire Slayer",
  valheim: "Valheim",
  ventrilo: "Ventrilo",
  vcmp: "Vice City Multiplayer",
  vietcong: "Vietcong",
  vietcong2: "Vietcong 2",
  warfork: "Warfork",
  warsow: "Warsow",
  wheeloftime: "Wheel of Time",
  wolfenstein2009: "Wolfenstein 2009",
  wolfensteinet: "Wolfenstein: Enemy Territory",
  wurm: "Wurm: Unlimited",
  xpandrally: "Xpand Rally",
  zombiemaster: "Zombie Master",
  zps: "Zombie Panic: Source",
};
